config/routes.rb
Rails.application.routes.draw do
  get 'pages/secret'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # Add a root route if you don't have one...
	# We can use users#new for now, or replace this with the controller and action you want to be the site root:
	root to: 'users#new'

  delete '/users', to: 'users#destroy', as: 'delete_user'
  	
  # sign up page with form:
  get 'users/new' => 'users#new'

  # create (post) action for when sign up form is submitted:
  post 'users' => 'users#create'

  # log in page with form:
	get '/login'     => 'sessions#new'
	
	# create (post) action for when log in form is submitted:
	post '/login'    => 'sessions#create'
	
	# delete action to log out:
	get '/logout' => 'sessions#destroy'  

  


  resources :users, only: [:index] do
    post :block, on: :collection
    post :unblock, on: :collection
  end

  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

	# Verify that email field is not blank and that it doesn't already exist in the db (prevents duplicates):
	validates :email, presence: true, uniqueness: true

    # ############################
    enum status: { active: 0, blocked: 1 } # Define status enum

    def block!
        update(status: :blocked)
    end

    def unblock!
        update(status: :active)
    end

    before_create :set_registration_time

    def set_registration_time
        self.registration_time = Time.zone.now
    end

    def update_last_login_time
        self.last_login_time = Time.zone.now
        save
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
     # Make the current_user method available to views also, not just controllers:
  helper_method :current_user
  
  # Define the current_user method:
  def current_user
    # Look up the current user based on user_id in the session cookie:
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  # authroize method redirects user to login page if not logged in:
  def authorize
    redirect_to login_path, alert: 'You must be logged in to access this page.' if current_user.nil?
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # Restrict access so only logged in users can access the secret page:
  before_action :authorize, only: [:secret]

  def secret
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        # No need for anything in here, we are just going to render our
        # new.html.erb AKA the login page
      end
    
      def create
        # Look up User in db by the email address submitted to the login form and
        # convert to lowercase to match email in db in case they had caps lock on:
        user = User.find_by(email: params[:login][:email].downcase)
        
        # Verify user exists in db and run has_secure_password's .authenticate() 
        # method to see if the password submitted on the login form was correct: 
        if user && user.authenticate(params[:login][:password]) 
          if user.active?  # Check if the user is active
            # Save the user.id in that user's session cookie:
            user.update_last_login_time
            session[:user_id] = user.id.to_s
            redirect_to users_path, notice: 'Successfully logged in!'
          else
            flash.now.alert = "Your account is blocked."
            render :new
          end
        else
          # if email or password incorrect, re-render login page:
          flash.now.alert = "Incorrect email or password, try again."
          render :new
        end
      end
    
      def destroy
        # delete the saved user_id key/value from the cookie:
        session.delete(:user_id)
        redirect_to login_path, notice: "Logged out!"
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)

        # @user.status = :active
        
        # store all emails in lowercase to avoid duplicates and case-sensitive login errors:
        @user.email.downcase!
        
        if @user.save
            # If user saves in the db successfully:
            flash[:notice] = "Account created successfully!"
            redirect_to login_path
        else
            # If user fails model validation - probably a bad password or duplicate email:
            flash.now.alert = "Oops, couldn't create account. Please make sure you are using a valid email and password and try again."
            render :new
        end
    end
        

    # ##############################
    before_action :authorize, except: [:new, :create]

    def index
        @users = User.all
    end
    
    # def block
    #   users = User.where(id: params[:user_ids])
    #   users.update_all(status: :blocked)
    #   redirect_to users_path, notice: 'Users blocked successfully!'
    # end

    def block
      users = User.where(id: params[:user_ids])
      
      # Check if current user is among the blocked users
      if users.pluck(:id).include?(current_user.id)
        users.each { |user| user.update(status: :blocked) }
        session.delete(:user_id)
        redirect_to login_path, notice: "You have blocked your account."
        return
      end
    
      users.each { |user| user.update(status: :blocked) }
      redirect_to users_path, notice: 'Users blocked successfully!'
    end
    
  
    def unblock
      users = User.where(id: params[:user_ids])
      users.update_all(status: :active)
      redirect_to users_path, notice: 'Users unblocked successfully!'
    end
  
    def destroy
      users = User.where(id: params[:user_ids])
   
      users.destroy_all
      # Log out the current user
      session.delete(:user_id)
  
    
      redirect_to login_path, notice: "Your account has been deleted."
      return
    
      # If the current user is not being deleted, simply delete the selected users
      users.destroy_all
      redirect_to users_path, notice: 'Users deleted successfully!'
    end
    
    
      

    ###############################

    
    private
    
    def user_params
    # strong parameters - whitelist of allowed fields #=> permit(:name, :email, ...)
    # that can be submitted by a form to the user model #=> require(:user)
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>User Management Application</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css' %>
    <!-- Application CSS -->
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <!-- Add this line to your HTML layout -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
  <div class="container">
    <!-- Brand/logo -->
    <a class="navbar-brand" href="<%= root_path %>">User Management App</a>

    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Navbar links -->
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <% if current_user %>
          <!-- Show user email if logged in -->
          <li class="nav-item">
  <span class="navbar-text text-dark">
    Hello, <%= current_user.name %>!
  </span>
</li>

          <!-- Log out link -->
          <li class="nav-item">
            <%= link_to 'Log Out', logout_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <!-- Log in and sign up links if not logged in -->
          <li class="nav-item">
            <%= link_to 'Log In', login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', users_new_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>



<div class="container">
<!-- Bootstrap alert to display alerts -->
<% if notice %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger" role="alert">
    <%= alert %>
  </div>
<% end %>
</div>
</div>

<div class="container">
  <%= yield %>
</div>


    <!-- Bootstrap JavaScript -->
    <%= javascript_include_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js' %>
    <!-- Application JavaScript -->
    <%= javascript_importmap_tags %>
  </body>
</html>

app/views/users/index.html.erb
<!-- app/views/users/index.html.erb -->

<!-- <h1>User Management</h1> -->

<%= form_with(url: block_users_path, method: :post) do %>
  <div class="btn-toolbar mb-4" role="toolbar">
  <div class="btn-group mr-2" role="group">
    <!-- Block button with icon and text -->
    <%= button_tag type: "submit", class: "btn btn-light mr-2", title: "Block" do %>
      <i class="fas fa-lock"></i> Block
    <% end %>

    <!-- Unblock button with icon only -->
    <%= button_tag type: "button", class: "btn btn-light mr-2", onclick: "unblockUsers()", title: "Unblock" do %>
      <i class="fas fa-lock-open"></i>
    <% end %>

    <!-- Delete button with icon only -->
    <%= button_tag type: "button", class: "btn btn-danger", onclick: "deleteUsers()", title: "Delete" do %>
      <i class="fas fa-trash-alt"></i>
    <% end %>
  </div>
</div>


  <table class="table">
    <thead>
      <tr>
        <th scope="col"><input type="checkbox" id="select-all" onchange="toggleCheckboxes()"></th>
        <th scope="col">ID</th>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Last Login Time</th>
        <th scope="col">Registration Time</th>
        <th scope="col">Status</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= check_box_tag 'user_ids[]', user.id %></td>
          <td><%= user.id %></td>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.last_login_time.strftime("%H:%M:%S, %d %b, %Y") %></td>
          <td><%= user.created_at.strftime("%H:%M:%S, %d %b, %Y") %></td>
          <td><%= user.status %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>


<script>
  function toggleCheckboxes() {
    const checkboxes = document.querySelectorAll('input[type=checkbox]');
    const selectAllCheckbox = document.getElementById('select-all');
    checkboxes.forEach((checkbox) => {
      checkbox.checked = selectAllCheckbox.checked;
    });
  }

  function getSelectedUserIds() {
  const checkboxes = document.querySelectorAll('input[type=checkbox]:checked');
  const ids = [];
  checkboxes.forEach((checkbox) => {
    
    const user_ids = checkbox.value.split(',').map(id => id.trim());
    
    ids.push(...user_ids);
  });
  return ids;
}



  function unblockUsers() {
    document.getElementById('user_ids').value = getSelectedUserIds();
    document.getElementById('unblock-form').submit();
  }

  function deleteUsers() {
    document.getElementById('delete_user_ids').value = getSelectedUserIds(); // Update the ID of the delete form's hidden field
    document.getElementById('delete-form').submit();
  }


</script>

<%= form_with(url: unblock_users_path, method: :post, id: 'unblock-form') do %>
  <%= hidden_field_tag 'user_ids[]', '', id: 'user_ids' %>
<% end %>

<%= form_with(url: users_path, method: :delete, id: 'delete-form') do %>
  <%= hidden_field_tag 'user_ids[]', '', id: 'delete_user_ids' %> <!-- Updated ID for the delete form's hidden field -->
  <!-- Add a submit button to trigger the form submission -->
  <%= submit_tag 'Delete', class: 'btn btn-outline-danger', style: 'display: none;' %>
<% end %>

app/views/users/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1>Sign Up</h1>

      <%= form_for @user, html: { class: "needs-validation", novalidate: true } do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control", autofocus: true, required: true %>
          <div class="invalid-feedback">
            Please provide a name.
          </div>
        </div>

        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: "form-control", required: true %>
          <div class="invalid-feedback">
            Please provide a valid email.
          </div>
        </div>

        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: "form-control", required: true %>
          <div class="invalid-feedback">
            Please provide a password.
          </div>
        </div>

        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: "form-control", required: true %>
          <div class="invalid-feedback">
            Please confirm your password.
          </div>
        </div>

        <div class="form-group">
          <%= f.submit "Sign Up", class: "btn btn-primary btn-block" %>
        </div>
      <% end %>

      <script>
        // Client-side form validation using Bootstrap's validation styles
        // Example taken from Bootstrap documentation: https://getbootstrap.com/docs/4.6/components/forms/#validation
        (function() {
          'use strict';

          window.addEventListener('load', function() {
            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            var forms = document.getElementsByClassName('needs-validation');

            // Loop over them and prevent submission
            var validation = Array.prototype.filter.call(forms, function(form) {
              form.addEventListener('submit', function(event) {
                if (form.checkValidity() === false) {
                  event.preventDefault();
                  event.stopPropagation();
                }
                form.classList.add('was-validated');
              }, false);
            });
          }, false);
        })();
      </script>
    </div>
  </div>
</div>